name:                git-stats
version:             0.1.0.0
github:              "githubuser/git-stats"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/git-stats#readme>

dependencies:
- base >= 4.7 && < 5
- process
- process-extras
- megaparsec >= 7
- containers
- async
- text
- prettyprinter
- prettyprinter-ansi-terminal

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-name-shadowing

executables:
  git-stats-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -Wno-unused-do-bind
    - -Wno-name-shadowing
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-stats

tests:
  git-stats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-stats
